### ISSUE TITLE
Create GitHub workflow

### ISSUE THREAD

**Issue by mistyayn** [krogebry/ironbark-k8s-self-service#27]
Build container and do CI

**Comment by mistyayn** [comment]
@krogebry can you please add some more details to this ticket in terms of what we are trying to accomplish with the workflow?

**Comment by krogebry** [comment]
# DoD

* Upon any commit to a branch on a PR, run the docker buildx for the frontend Dockerfile
* When merged to main, do the docker buildx again.  Eventually we'll have the image pushed to a repository on the k8s cluster using our own runners.

# References

* Github actions: https://docs.docker.com/build/ci/github-actions/

# Why?

This acts as a basic gut check for building the application.  Eventually we want to start adding linting and unit testing mechanisms in here as well.
